services:
  - type: worker
    name: kasbiy-talim-ishonch-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
        
      - key: BOT_TOKEN
        value: '8860601189:AAFpnru0P2eIk4D4_HXEqYo5jLeBT2UWR4Y'

      - key: CONTACT_PHONE
        value: "+998 91 304 00 09"
